version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing Terraform"
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - terraform validate

  build:
    commands:
      - echo "Running Terraform Plan..."
      - terraform plan -out=tfplan

artifacts:
  files:
    - tfplan
